services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: {{ postgres_user }}
      POSTGRES_PASSWORD: {{ postgres_password }}
      POSTGRES_DB: {{ postgres_db }}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ta_hsx_net

volumes:
  postgres_data:

networks:
  ta_hsx_net: