- name: Ensure app-stack directory exists
  file:
    path: "{{ app_stack_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yaml to remote
  copy:
    src: "../files/docker-compose.yaml"
    dest: "{{ app_stack_dir }}/docker-compose.yaml"

- name: Copy .env to remote
  copy:
    src: "../files/.env"
    dest: "{{ docker_env_file }}"
    mode: '0644'

- name: Deploy containers with Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ app_stack_dir }}"