name: Rollout Technical Assessment HSX

on: workflow_dispatch

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_VAR_ssh_public_key: "${{ secrets.SSH_PUBLIC_KEY }}"

jobs:
  Rollout-Technical-Assessment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve